# Generated by Django 4.0.4 on 2022-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('normal', 'Normal'), ('wikidot', 'Wikidot'), ('system', 'System')], default='normal', verbose_name='Тип'),
        ),
    ]
