# Generated by Django 4.0.4 on 2022-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='-/users', verbose_name='Аватар'),
        ),
    ]
