# Generated by Django 4.0.6 on 2022-07-23 21:49

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wikidot_username',
            field=django.contrib.postgres.fields.citext.CITextField(null=True, unique=True, verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
