# Generated by Django 4.0.4 on 2022-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/images/default_avatar.png', upload_to='-/users', verbose_name='Аватар'),
        ),
    ]
