# Generated by Django 4.0.6 on 2022-08-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_user_wikidot_username'),
    ]

    operations = [
        migrations.RunSQL("update system_user set wikidot_username=username where wikidot_username is null and username != 'AnonymousUser'")
    ]
