# Generated by Django 4.0.6 on 2022-08-16 01:15

import django.contrib.auth.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_set_wd_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wikidot_username',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
