# Generated by Django 4.1.2 on 2022-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_user_wikidot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=67, null=True, unique=True, verbose_name='Апи-ключ (для ботов)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('normal', 'Normal'), ('wikidot', 'Wikidot'), ('system', 'System'), ('bot', 'Bot')], default='normal', verbose_name='Тип'),
        ),
    ]
