# Generated by Django 4.1.2 on 2022-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_user_api_key_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=67, null=True, unique=True, verbose_name='Апи-ключ'),
        ),
    ]
