# Generated by Django 4.0.6 on 2023-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_user_forum_inactive_until_user_inactive_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Статус участника'),
        ),
    ]
