# Generated by Django 4.0.6 on 2023-08-12 16:43

import django.contrib.auth.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_user_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Токен')),
                ('is_case_sensitive', models.BooleanField(default=True, verbose_name='Чувствителен к регистру')),
            ],
            options={
                'verbose_name': 'Использованный токен',
                'verbose_name_plural': 'Использованные токены',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(error_messages={'unique': 'Пользователь с данным именем уже существует'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wikidot_username',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
