# Generated by Django 4.1.10 on 2024-05-11 18:03

import django.contrib.postgres.fields.citext
from django.db import migrations
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_usedtoken_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(error_messages={'unique': 'Пользователь с данным именем уже существует'}, max_length=150, unique=True, validators=[system.models.StrictUsernameValidator()], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wikidot_username',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=150, null=True, unique=True, validators=[system.models.StrictUsernameValidator()], verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
