# Generated by Django 4.0.6 on 2024-09-22 15:12

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_user_username_alter_user_wikidot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Визуальная группа',
                'verbose_name_plural': 'Визуальные группы',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='visual_group',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.visualusergroup', verbose_name='Визуальная группа'),
        ),
    ]
