# Generated by Django 4.0.6 on 2024-10-26 00:27

import auto_prefetch
from django.db import migrations
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_visualusergroup_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visual_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.visualusergroup', verbose_name='Визуальная группа'),
        ),
    ]
