# Generated by Django 5.1.4 on 2025-01-08 10:56

import system.fields
import system.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_user_username_alter_user_wikidot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=system.fields.CITextField(error_messages={'unique': 'Пользователь с данным именем уже существует'}, max_length=150, unique=True, validators=[system.models.StrictUsernameValidator()], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wikidot_username',
            field=system.fields.CITextField(max_length=150, null=True, unique=True, validators=[system.models.StrictUsernameValidator()], verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
