# Generated by Django 5.1.4 on 2025-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_alter_user_username_alter_user_wikidot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('normal', 'Обычный'), ('wikidot', 'Пользователь Wikidot'), ('system', 'Системный'), ('bot', 'Бот')], default='normal', verbose_name='Тип'),
        ),
    ]
