# Generated by Django 4.0.4 on 2022-06-13 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='_default', verbose_name='Категория')),
                ('name', models.TextField(verbose_name='Имя')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'permissions': [('can_vote_article', 'Может голосовать за статью')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('source', 'Source'), ('title', 'Title'), ('name', 'Name'), ('tags', 'Tags'), ('new', 'New'), ('parent', 'Parent')], verbose_name='Тип')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('rev_number', models.PositiveIntegerField(verbose_name='Номер правки')),
            ],
            options={
                'verbose_name': 'Запись в журнале изменений',
                'verbose_name_plural': 'Записи в журнале изменений',
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='Исходник')),
                ('rendered', models.TextField(blank=True, null=True, verbose_name='Рендер статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Версия статьи',
                'verbose_name_plural': 'Версии статей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'permissions': [('add_article_in_category', 'Может добавлять новые статьи в категорию'), ('change_article_in_category', 'Может изменять статьи в категории'), ('delete_article_in_category', 'Может удалять статьи в категории'), ('can_vote_article_in_category', 'Может голосовать за статьи в категории')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='Статья')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='web_tag_name_41cd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='web_tag_unique'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='web_categor_name_e51bae_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='web_category_unique'),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articlelogentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='web.tag', verbose_name='Тэги'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='web_vote_unique'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article', 'created_at'], name='web_article_article_eb894c_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlelogentry',
            constraint=models.UniqueConstraint(fields=('article', 'rev_number'), name='web_articlelogentry_unique'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'name'], name='web_article_categor_006394_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='web_article_unique'),
        ),
    ]
