# Generated by Django 4.0.3 on 2022-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article', 'created_at'], name='web_article_article_eb894c_idx'),
        ),
    ]
