# Generated by Django 4.0.6 on 2022-07-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='type',
            new_name='rating_mode',
        ),
        migrations.RemoveField(
            model_name='category',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='site',
            name='settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='web.category'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='web.site'),
        ),
    ]
