# Generated by Django 4.0.3 on 2022-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_articleversion_web_article_article_eb894c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleversion',
            name='rendered',
            field=models.TextField(null=True),
        ),
    ]
