# Generated by Django 4.0.6 on 2022-07-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_settings_rating_mode_alter_vote_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='rating_mode',
            field=models.TextField(choices=[('default', 'Default'), ('disabled', 'Disabled'), ('updown', 'Updown'), ('stars', 'Stars')], default='default', verbose_name='Система рейтинга'),
        ),
    ]
