# Generated by Django 4.0.4 on 2022-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_articlelogentry_type_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
