# Generated by Django 4.0.3 on 2022-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_articlelogentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlelogentry',
            constraint=models.UniqueConstraint(fields=('article', 'rev_number'), name='web_articlelogentry_unique'),
        ),
    ]
