# Generated by Django 4.0.3 on 2022-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_articlelogentry_web_articlelogentry_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='meta',
            field=models.JSONField(default={}),
        ),
    ]
