# Generated by Django 4.0.6 on 2022-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_externallink_externallink_web_externallink_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleversion',
            name='ast',
            field=models.TextField(blank=True, null=True, verbose_name='AST-дерево статьи'),
        ),
    ]
