# Generated by Django 4.0.6 on 2022-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_articleversion_ast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleversion',
            name='ast',
            field=models.JSONField(blank=True, null=True, verbose_name='AST-дерево статьи'),
        ),
    ]
