# Generated by Django 4.0.6 on 2022-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_articleversion_ast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_create',
            field=models.BooleanField(default=True, verbose_name='Пользователи могут создавать статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_delete',
            field=models.BooleanField(default=True, verbose_name='Пользователи могут удалять статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_edit',
            field=models.BooleanField(default=True, verbose_name='Пользователи могут редактировать статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_rate',
            field=models.BooleanField(default=True, verbose_name='Пользователи могут голосовать за статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_view',
            field=models.BooleanField(default=True, verbose_name='Пользователи могут просматривать статьи'),
        ),
    ]
