# Generated by Django 4.0.4 on 2022-07-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_articlelogentry_type'),
        ('web', '0007_site_icon'),
    ]

    operations = [
    ]
