# Generated by Django 4.0.6 on 2022-08-14 04:51

from django.db import migrations
import re
import logging


# This migration converts [[div class="rimg"]] into [[div_ class="rimg"]]
# See https://github.com/SCPru/RuFoundation/issues/51


# logic: [[div<ANYTHING>class="<ANYTHING>"<ANYTHING>]]
regex = r'\[\[div([^_\]]*)class="([^"]*)"([^\]]*)\]\]'


def replacer(match):
    before, cls, after = match.groups()
    if 'rimg' not in cls.split(' '):
        return match[0]
    return '[[div_%sclass="%s"%s]]' % (before, cls, after)


def convert_rimg(apps, schema_editor):
    Article = apps.get_model("web", "Article")
    ArticleVersion = apps.get_model("web", "ArticleVersion")
    db = schema_editor.connection.alias
    articles = Article.objects.using(db).all()
    total = len(articles)
    done = -1
    for article in articles:
        done += 1
        if (done and done % 100 == 0) or done == total - 1:
            print('%d...' % done, end='')
            import sys
            sys.stdout.flush()
        latest_version = ArticleVersion.objects.using(db).filter(article=article).order_by('-created_at')
        if not latest_version:
            continue
        latest_version = latest_version[0]
        new_source = re.sub(regex, replacer, latest_version.source)
        if new_source != latest_version.source:
            # cba adding proper version to the article, let's just do it in-place
            latest_version.source = new_source
            latest_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_assign_author_to_articles'),
    ]

    operations = [
        migrations.RunPython(convert_rimg, atomic=True)
    ]
