# Generated by Django 4.0.4 on 2022-05-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_articlelogentry_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlelogentry',
            options={'verbose_name': 'Запись в журнале изменений', 'verbose_name_plural': 'Записи в журнале изменений'},
        ),
        migrations.AlterModelOptions(
            name='articleversion',
            options={'verbose_name': 'Версия статьи', 'verbose_name_plural': 'Версии статей'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.TextField(default='_default', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='meta',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='rev_number',
            field=models.PositiveIntegerField(verbose_name='Номер правки'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', 'Source'), ('title', 'Title'), ('name', 'Name'), ('new', 'New'), ('parent', 'Parent')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='rendered',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Рендер статьи'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='source',
            field=models.TextField(verbose_name='Исходник'),
        ),
    ]
