# Generated by Django 4.0.4 on 2022-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_article_options_article_author_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='web.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', 'Source'), ('title', 'Title'), ('name', 'Name'), ('tags', 'Tags'), ('new', 'New'), ('parent', 'Parent')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
    ]
