# Generated by Django 4.0.6 on 2022-08-16 01:20
from pathlib import Path
from uuid import uuid4

from django.conf import settings
from django.db import migrations, models

import os


def get_full_name(article):
    if article.category == '_default':
        return article.name
    else:
        return '%s:%s' % (article.category, article.name)


def partial_quote(url):
    return url.replace(':', '%3A').replace('/', '%2F').replace('?', '%3F')


def rename_media_folders(apps, schema_editor):
    Article = apps.get_model("web", "Article")
    ArticleLogEntry = apps.get_model("web", "ArticleLogEntry")
    db = schema_editor.connection.alias
    for article in Article.objects.using(db).all():
        # find renames, if any.
        renames = ArticleLogEntry.objects.using(db).filter(article=article, type='name').order_by('-rev_number')
        real_current_dir_name = get_full_name(article)
        for rename in renames:
            if real_current_dir_name == rename.meta['name']:
                real_current_dir_name = rename.meta['prev_name']
            else:
                raise ValueError('Integrity error: expected rename to be %s, found %s instead' % (real_current_dir_name, rename.meta['name']))
        path_rename_from = Path(settings.MEDIA_ROOT) / article.site.slug / partial_quote(real_current_dir_name)
        path_rename_to = Path(settings.MEDIA_ROOT) / article.site.slug / article.media_name
        if os.path.exists(path_rename_from):
            os.rename(path_rename_from, path_rename_to)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_assign_uuid_to_articles'),
    ]

    operations = [
        migrations.RunPython(rename_media_folders),
        migrations.AlterField(
            model_name='article',
            name='media_name',
            field=models.TextField(default=uuid4, unique=True, verbose_name='Название папки с файлами в ФС-хранилище'),
        ),
    ]
