# Generated by Django 4.0.4 on 2022-06-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_tag_options_alter_article_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
