# Generated by Django 4.0.6 on 2022-08-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_delete_external_links'),
    ]

    operations = [
        migrations.RunSQL('update web_article set name=lower(name), category=lower(category)'),
        migrations.RunSQL('update web_externallink set link_from=lower(link_from), link_to=lower(link_to)')
    ]
