# Generated by Django 4.0.4 on 2022-06-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_vote_article_alter_vote_rate_alter_vote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_vote_article', 'Can voting for an article')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
