# Generated by Django 4.0.4 on 2022-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='rendered',
            field=models.TextField(blank=True, null=True, verbose_name='Рендер статьи'),
        ),
    ]
