# Generated by Django 4.0.4 on 2022-06-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_articlelogentry_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='Статья'),
        ),
    ]
