# Generated by Django 4.0.6 on 2022-08-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_category_users_can_comment_forumpost_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Пришпилено'),
        ),
    ]
