# Generated by Django 4.0.6 on 2022-08-28 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_forumthread_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumthread',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Время удаления'),
        ),
    ]
