# Generated by Django 4.0.4 on 2022-06-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('add_article_in_category', 'Может добавлять новые статьи в категорию'), ('change_article_in_category', 'Может изменять статьи в категории'), ('delete_article_in_category', 'Может удалять статьи в категории'), ('can_vote_article_in_category', 'Может голосовать за статьи в категории')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
