# Generated by Django 4.0.6 on 2022-08-28 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0023_forumpostversion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpostversion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор правки'),
        ),
    ]
