# Generated by Django 4.0.6 on 2022-09-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_category_options_alter_articleversion_article_and_more'),
        ('web', '0024_forumpostversion_author'),
    ]

    operations = [
    ]
