# Generated by Django 4.1.2 on 2022-12-02 13:56

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0027_tagscategory_remove_tag_web_tag_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlelogentry',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Запись в журнале изменений', 'verbose_name_plural': 'Записи в журнале изменений'},
        ),
        migrations.AlterModelOptions(
            name='articleversion',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Версия статьи', 'verbose_name_plural': 'Версии статей'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Настройки категории', 'verbose_name_plural': 'Настройки категорий'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Раздел форума', 'verbose_name_plural': 'Разделы форума'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Сообщение форума', 'verbose_name_plural': 'Сообщения форума'},
        ),
        migrations.AlterModelOptions(
            name='forumpostversion',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Версия сообщения форума', 'verbose_name_plural': 'Версии сообщений форума'},
        ),
        migrations.AlterModelOptions(
            name='forumsection',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Категория форума', 'verbose_name_plural': 'Категории форума'},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Тема форума', 'verbose_name_plural': 'Темы форума'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagscategory',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Категория тегов', 'verbose_name_plural': 'Категории тегов'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articlelogentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articleversion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externallink',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='file',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumcategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumpost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumpostversion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumsection',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumthread',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='settings',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tagscategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vote',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='category',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='file',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='Автор файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='deleted_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, удаливший файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='section',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumsection', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='reply_to',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.forumpost', verbose_name='Ответ на комментарий'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='thread',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор правки'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='post',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumpost', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forumsection',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='article',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья (если это комментарии)'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumcategory', verbose_name='Раздел (если это тема)'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='category',
            field=auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.category'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site',
            field=auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.site'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tagscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
