# Generated by Django 4.1.2 on 2022-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_update_tags_in_log_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='can_user_create_tags',
            field=models.TextField(choices=[('default', 'Default'), ('disabled', 'Disabled'), ('enabled', 'Enabled')], default='default', verbose_name='Может ли пользователь создавать теги'),
        ),
    ]
