# Generated by Django 4.0.6 on 2023-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_settings_can_user_create_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата голоса'),
        ),
    ]
