# Generated by Django 4.0.6 on 2023-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_vote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='readers_can_comment',
            field=models.BooleanField(default=True, verbose_name='Читатели могут комментировать статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='readers_can_create',
            field=models.BooleanField(default=False, verbose_name='Читатели могут создавать статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='readers_can_delete',
            field=models.BooleanField(default=False, verbose_name='Читатели могут удалять статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='readers_can_edit',
            field=models.BooleanField(default=False, verbose_name='Читатели могут редактировать статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='readers_can_rate',
            field=models.BooleanField(default=True, verbose_name='Читатели могут голосовать за статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='readers_can_view',
            field=models.BooleanField(default=True, verbose_name='Читатели могут просматривать статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_comment',
            field=models.BooleanField(default=True, verbose_name='Авторы могут комментировать статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_create',
            field=models.BooleanField(default=True, verbose_name='Авторы могут создавать статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_delete',
            field=models.BooleanField(default=False, verbose_name='Авторы могут удалять статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_edit',
            field=models.BooleanField(default=True, verbose_name='Авторы могут редактировать статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_rate',
            field=models.BooleanField(default=True, verbose_name='Авторы могут голосовать за статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_can_view',
            field=models.BooleanField(default=True, verbose_name='Авторы могут просматривать статьи'),
        ),
    ]
