# Generated by Django 4.0.6 on 2023-05-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_category_readers_can_comment_and_more'),
    ]

    operations = [
        migrations.RunSQL('UPDATE "system_user" SET is_editor=TRUE'),
    ]
