# Generated by Django 4.0.6 on 2024-09-22 16:23

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_visualusergroup_index'),
        ('web', '0036_externallink_web_externa_link_fr_92155a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='visual_group',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.visualusergroup', verbose_name='Визуальная группа'),
        ),
    ]
