# Generated by Django 5.0.6 on 2024-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_articlelogentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='link_from',
            field=models.TextField(db_collation='en_ci', verbose_name='Ссылающаяся статья'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_to',
            field=models.TextField(db_collation='en_ci', verbose_name='Целевая статья'),
        ),
    ]
