# Generated by Django 5.1.4 on 2025-01-08 10:56

import system.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_externallink_link_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='link_from',
            field=system.fields.CITextField(verbose_name='Ссылающаяся статья'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_to',
            field=system.fields.CITextField(verbose_name='Целевая статья'),
        ),
    ]
