# Generated by Django 5.1.4 on 2025-02-06 18:24

import web.models.articles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_site_options_alter_site_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', 'Изменение содержимого'), ('title', 'Изменение заголовка'), ('name', 'Изменение адреса страницы'), ('tags', 'Изменение тегов'), ('new', 'Создание страницы'), ('parent', 'Изменение родителя'), ('file_added', 'Добавление файлов'), ('file_deleted', 'Удаление файлов'), ('file_renamed', 'Переименование файлов'), ('votes_deleted', 'Сброс рейтинга'), ('wikidot', 'Правка с Wikidot'), ('revert', 'Откат правки')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='can_user_create_tags',
            field=models.TextField(choices=[('default', 'По умолчанию'), ('disabled', 'Запрещено'), ('enabled', 'Разрешено')], default='default', verbose_name='Может ли пользователь создавать теги'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rating_mode',
            field=models.TextField(choices=[('default', 'По умолчанию'), ('disabled', 'Отключено'), ('updown', 'Апвоуты'), ('stars', 'Звёзды')], default='default', verbose_name='Система рейтинга'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='slug',
            field=models.TextField(unique=True, validators=[web.models.articles.TagsCategorySlugValidator()], verbose_name='Идентификатор'),
        ),
    ]
