# Generated by Django 5.1.4 on 2025-02-18 08:39

import auto_prefetch
import django.db.models.deletion
import web.models.articles
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_migrate_system_to_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=auto_prefetch.ForeignKey(default=web.models.articles.TagsCategory.get_or_create_default_tags_category, on_delete=django.db.models.deletion.CASCADE, to='web.tagscategory', verbose_name='Категория'),
        ),
    ]
