# Generated by Django 5.1.4 on 2025-03-07 10:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stale_username', models.TextField(verbose_name='Имя на момент действия')),
                ('type', models.TextField(choices=[('vote', 'Оценка'), ('create_article', 'Страница создана'), ('edit_article', 'Страница отредактирована'), ('remove_article', 'Страница удалена'), ('add_forum_post', 'Сообщение форума создано'), ('edit_forum_post', 'Сообщение форума изменено'), ('remove_forum_post', 'Сообщение форума удалено'), ('change_profile_info', 'Информация профиля изменена')], verbose_name='Тип')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('origin_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
