# Generated by Django 5.1.4 on 2025-03-29 00:00

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_actionlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('welcome', 'Приветственное сообщение'), ('new_post_reply', 'Ответ на пост'), ('new_thread_post', 'Новый пост'), ('new_article_revision', 'Правка статьи')], verbose_name='Тип уведомлнения')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('referred_to', models.TextField(blank=True, null=True, verbose_name='Ведет к')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.TextField(choices=[('welcome', 'Приветственное сообщение'), ('new_post_reply', 'Ответ на пост'), ('new_thread_post', 'Новый пост'), ('new_article_revision', 'Правка статьи')], unique=True, verbose_name='Тип уведомлнения')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.TextField(choices=[('vote', 'Оценка'), ('create_article', 'Страница создана'), ('edit_article', 'Страница отредактирована'), ('remove_article', 'Страница удалена'), ('add_forum_post', 'Новое сообщение форума'), ('edit_forum_post', 'Сообщение форума изменено'), ('remove_forum_post', 'Сообщение форума удалено'), ('change_profile_info', 'Информация профиля изменена')], verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='UserNotificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usernotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья')),
                ('forum_thread', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='Ветка форума')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
