# Generated by Django 5.1.4 on 2025-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_delete_usernotificationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_indexed',
            field=models.BooleanField(default=True, verbose_name='Индексируется поисковиками'),
        ),
    ]
