# Generated by Django 5.1.4 on 2025-04-30 00:20

import os
from pathlib import Path
from django.conf import settings
from django.db import migrations


def rename_media_folders(apps, schema_editor):
    Site = apps.get_model("web", "Site")
    media_root = Path(settings.MEDIA_ROOT)
    new_media_folder = media_root / 'media'

    if Site.objects.exists():
        slug: str = Site.objects.get().slug
        slug_folder = media_root / slug
        if slug_folder.exists():
            os.rename(slug_folder, new_media_folder)
    elif not new_media_folder.exists():
        os.mkdir(new_media_folder)
            

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_category_is_indexed'),
    ]

    operations = [
        migrations.RunPython(rename_media_folders, migrations.RunPython.noop, atomic=True),
    ]
