# Generated by Django 5.1.4 on 2025-08-23 12:52

import web.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_rename_media_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualusergroup',
            name='badge',
            field=models.TextField(default='', verbose_name='Бейдж'),
        ),
        migrations.AddField(
            model_name='visualusergroup',
            name='badge_bg',
            field=models.TextField(default='#808080', validators=[web.models.users.CSSValueValidator()], verbose_name='Цвет бейджа'),
        ),
        migrations.AddField(
            model_name='visualusergroup',
            name='badge_text_color',
            field=models.TextField(default='#FFFFFF', validators=[web.models.users.CSSValueValidator()], verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='visualusergroup',
            name='show_badge',
            field=models.BooleanField(default=False, verbose_name='Показывать бейдж'),
        ),
    ]
