# Generated by Django 5.1.4 on 2025-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_visualusergroup_badge_visualusergroup_badge_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualusergroup',
            name='badge_show_border',
            field=models.BooleanField(default=False, verbose_name='Показывать границу'),
        ),
    ]
