# Generated by Django 5.1.4 on 2025-08-25 12:05

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_articlesearchindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesearchindex',
            options={'verbose_name': 'Индекс для поиска по статьям', 'verbose_name_plural': 'Индексы для поиска по статьям'},
        ),
        migrations.AlterModelManagers(
            name='articlesearchindex',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='articlesearchindex',
            new_name='web_article_vector__0d2eb2_gin',
            old_name='web_article_vector__7954ea_gin',
        ),
        migrations.AlterField(
            model_name='articlesearchindex',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Статья'),
        ),
        migrations.AddIndex(
            model_name='articlesearchindex',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('content_source'), name='gin_trgm_ops'), name='content_source_lower_trgm_gin'),
        ),
    ]
