# Generated by Django 5.1.4 on 2025-08-29 08:39

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_alter_articlesearchindex_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesearchindex',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': 'Индекс для поиска по статьям', 'verbose_name_plural': 'Индексы для поиска по статьям'},
        ),
        migrations.AlterModelManagers(
            name='articlesearchindex',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='articlesearchindex',
            name='article',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='usernotificationmapping',
            name='notification',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usernotification'),
        ),
        migrations.AlterField(
            model_name='usernotificationmapping',
            name='recipient',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernotificationsubscription',
            name='subscriber',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
