# Generated by Django 5.1.4 on 2025-09-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_create_built_in_roles_and_migrate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visual_group',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='visual_group',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_comment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_create',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_delete',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_edit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_rate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='readers_can_view',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_comment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_create',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_delete',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_edit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_rate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_can_view',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.DeleteModel(
            name='VisualUserGroup',
        ),
    ]
