# Generated by Django 5.1.4 on 2025-09-25 10:56

from django.db import migrations


def delete_broken_logs(apps, schema_editor):
    ActionLogEntry = apps.get_model("web", "ActionLogEntry")
    ActionLogEntry.objects.filter(type__in=["edit_forum_post", "remove_forum_post"]).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_remove_user_visual_group_remove_vote_visual_group_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_broken_logs, migrations.RunPython.noop),
    ]
