# Generated by Django 5.1.4 on 2025-09-26 11:52

import web.fields.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0059_remove_forum_post_edit_delete_event_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=web.fields.models.CITextField(default='_default', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=web.fields.models.CITextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=web.fields.models.CITextField(verbose_name='Имя'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['slug'], name='web_role_slug_06c2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['category'], name='web_role_categor_bd0076_idx'),
        ),
    ]
