# Generated by Django 5.1.4 on 2025-09-28 14:26

import django.db.models.functions.text
import web.fields.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_article_category_alter_article_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='web_article_categor_006394_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='complete_full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('category', models.Value(':', output_field=web.fields.models.CITextField()), 'name'), output_field=web.fields.models.CITextField()),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='web_article_categor_7c81ec_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name'], name='web_article_name_1c14b5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['complete_full_name'], name='web_article_complet_ea3782_idx'),
        ),
    ]
