# Generated by Django 5.1.4 on 2025-11-14 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_remove_article_web_article_categor_006394_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='authored_by', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
