# Generated by Django 5.1.4 on 2025-11-14 22:28

from django.db import migrations


def copy_fk_to_m2m(apps, schema_editor):
    Article = apps.get_model('web', 'Article')
    for instance in Article.objects.all():
        if instance.author:
            instance.authors.add(instance.author)

def reverse_copy_fk_to_m2m(apps, schema_editor):
    Article = apps.get_model('web', 'Article')
    for instance in Article.objects.all():
        if instance.authors.exists():
            instance.author = instance.authors.first()
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_article_authors'),
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, reverse_copy_fk_to_m2m)
    ]

