# Generated by Django 5.1.4 on 2025-11-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_author_to_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
