# Generated by Django 5.1.4 on 2025-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_remove_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', 'Изменение содержимого'), ('title', 'Изменение заголовка'), ('name', 'Изменение адреса страницы'), ('tags', 'Изменение тегов'), ('new', 'Создание страницы'), ('parent', 'Изменение родителя'), ('file_added', 'Добавление файлов'), ('file_deleted', 'Удаление файлов'), ('file_renamed', 'Переименование файлов'), ('votes_deleted', 'Сброс рейтинга'), ('authorship', 'Изменение авторства'), ('wikidot', 'Правка с Wikidot'), ('revert', 'Откат правки')], verbose_name='Тип'),
        ),
    ]
