# Generated by Django 5.1.4 on 2025-11-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_articlelogentry_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actionlogentry',
            index=models.Index(fields=['user', 'origin_ip'], name='user_origin_ip_idx'),
        ),
    ]
