# Generated by Django 5.1.4 on 2025-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_articlelogentry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='referred_to',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.TextField(choices=[('welcome', 'Приветственное сообщение'), ('new_post_reply', 'Ответ на пост'), ('new_thread_post', 'Новый пост'), ('new_article_revision', 'Правка статьи'), ('forum_mention', 'Упоминание на форуме')], verbose_name='Тип уведомления'),
        ),
    ]
