# Generated by Django 5.2.8 on 2026-04-25 07:53

import web.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_user_user_email_ci_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media_name',
            field=models.TextField(default=web.util.uuid4_str, unique=True, verbose_name='Название папки с файлами в ФС-хранилище'),
        ),
        migrations.AddConstraint(
            model_name='forumthread',
            constraint=models.UniqueConstraint(fields=('article',), name='web_forumthread_unique_article'),
        ),
    ]
