# Generated by Django 5.2.8 on 2026-06-22 21:41

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import web.models.forum
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_alter_article_media_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='forum_reaction_types_per_post',
            field=models.PositiveIntegerField(default=20, help_text='Сколько разных типов реакций можно показать под одним сообщением. Пользователи могут добавлять уже показанные типы сверх этого лимита. 0 отключает новые реакции.', verbose_name='Максимум типов реакций под сообщением'),
        ),
        migrations.AddField(
            model_name='settings',
            name='forum_reactions_per_user',
            field=models.PositiveIntegerField(default=20, help_text='Сколько разных реакций один пользователь может поставить под одним сообщением. 0 отключает новые реакции.', verbose_name='Максимум реакций пользователя под сообщением'),
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.TextField(choices=[('vote', 'Оценка'), ('create_article', 'Страница создана'), ('edit_article', 'Страница отредактирована'), ('remove_article', 'Страница удалена'), ('add_forum_post', 'Новое сообщение форума'), ('edit_forum_post', 'Сообщение форума изменено'), ('remove_forum_post', 'Сообщение форума удалено'), ('add_forum_reaction', 'Реакция на форуме добавлена'), ('remove_forum_reaction', 'Реакция на форуме удалена'), ('change_profile_info', 'Информация профиля изменена')], verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('image', models.FileField(upload_to='-/forum-reactions', validators=[web.models.forum.validate_forum_reaction_image], verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Реакция форума',
                'verbose_name_plural': 'Реакции форума',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['is_active'], name='forum_react_active_order_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('post', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='web.forumpost', verbose_name='Сообщение')),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reaction', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='web.forumreaction', verbose_name='Реакция')),
            ],
            options={
                'verbose_name': 'Реакция на сообщение форума',
                'verbose_name_plural': 'Реакции на сообщения форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['post', 'reaction'], name='fpost_react_post_reaction_idx'), models.Index(fields=['user'], name='fpost_react_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'reaction', 'user'), name='web_forumpostreaction_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
