# Generated by Django 5.2.8 on 2026-06-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_settings_forum_reaction_types_per_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreaction',
            options={
                'base_manager_name': 'prefetch_manager',
                'ordering': ['sort_order', 'id'],
                'verbose_name': 'Реакция форума',
                'verbose_name_plural': 'Реакции форума',
            },
        ),
        migrations.RemoveIndex(
            model_name='forumreaction',
            name='forum_react_active_order_idx',
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок сортировки'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['is_active', 'sort_order'], name='forum_react_active_order_idx'),
        ),
    ]
