# Generated by Django 5.2.8 on 2026-06-23 00:26

from django.db import migrations


def normalize_forum_reaction_sort_order(apps, schema_editor):
    ForumReaction = apps.get_model('web', 'ForumReaction')
    db_alias = schema_editor.connection.alias
    reactions = list(ForumReaction.objects.using(db_alias).order_by('sort_order', 'id'))

    for index, reaction in enumerate(reactions, start=1):
        reaction.sort_order = index

    if reactions:
        ForumReaction.objects.using(db_alias).bulk_update(reactions, ['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_forum_reaction_sort_order'),
    ]

    operations = [
        migrations.RunPython(normalize_forum_reaction_sort_order, migrations.RunPython.noop),
    ]
