# Generated by Django 5.2.8 on 2026-06-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_normalize_forum_reaction_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='forum_post_max_depth',
            field=models.PositiveIntegerField(
                default=5,
                help_text='Глубина отображения дерева ответов. Ответы глубже этого значения показываются на максимальном уровне вложенности.',
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Максимальная вложенность постов',
            ),
        ),
    ]
