# Generated by Django 5.2.8 on 2026-06-25 18:30:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_settings_forum_post_max_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Пришпилено'),
        ),
    ]
