# Generated by Django 5.2.8 on 2026-06-25 18:45:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_forumpost_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.TextField(
                choices=[
                    ('vote', 'Оценка'),
                    ('create_article', 'Страница создана'),
                    ('edit_article', 'Страница отредактирована'),
                    ('remove_article', 'Страница удалена'),
                    ('add_forum_post', 'Новое сообщение форума'),
                    ('edit_forum_post', 'Сообщение форума изменено'),
                    ('remove_forum_post', 'Сообщение форума удалено'),
                    ('pin_forum_post', 'Сообщение форума закреплено'),
                    ('unpin_forum_post', 'Сообщение форума откреплено'),
                    ('add_forum_reaction', 'Реакция на форуме добавлена'),
                    ('remove_forum_reaction', 'Реакция на форуме удалена'),
                    ('change_profile_info', 'Информация профиля изменена'),
                ],
                verbose_name='Тип',
            ),
        ),
    ]
