# Generated by Django 5.2.8 on 2026-06-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_alter_actionlogentry_type_for_forum_post_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_reactions_disabled_until',
            field=models.DateTimeField(null=True, verbose_name='Принудительно отключить реакции форума до'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_forum_reactions_disabled',
            field=models.BooleanField(default=False, verbose_name='Реакции форума принудительно отключены'),
        ),
    ]
