# Generated by Django 5.2.8 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0076_user_forum_reactions_disabled_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreaction',
            name='is_hidden_from_picker',
            field=models.BooleanField(
                default=False,
                help_text='Скрытая реакция не показывается в пикере и не может быть добавлена никем, включая администраторов.',
                verbose_name='Скрыть в пикере',
            ),
        ),
    ]
