# Generated by Django 5.2.8 on 2026-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_forumreaction_is_hidden_from_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rating_visibility_mode',
            field=models.TextField(choices=[('always', 'Отображать всегда'), ('after_vote', 'Отображать после оценки')], default='always', verbose_name='Отображение рейтинга'),
        ),
    ]
