# Generated by Django 5.2.8 on 2026-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_settings_rating_visibility_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='rating_visibility_mode',
            field=models.TextField(choices=[('always', 'Отображать всегда'), ('after_vote', 'Отображать после оценки'), ('hidden', 'Всегда скрыт')], default='always', verbose_name='Отображение рейтинга'),
        ),
    ]
